-- 0. CLEAN SLATE (Idempotency)
-- Using CASCADE to handle dependencies automatically
TRUNCATE TABLE users, locations, devices, vlans, interfaces, interface_vlans, links, events, device_metrics, audit_logs, user_location_access CASCADE;

-- ==================================================================================
-- 1. IDENTITY & ACCESS (Users)
-- ==================================================================================
-- A) Static Core Users
INSERT INTO users (first_name, last_name, email, username, password, role, inactive_status, mfa_enabled, last_login) VALUES
('Admin',  'User', 'admin@example.com',  'admin',  '$argon2id$v=19$m=65536,t=1,p=4$X3Y4GbVV8pnrXFl/RHL3xw$7DDEkAYfAqeB14mhBFYajtMxGt24h+tIj8fJrmxXeXw', 'admin',  FALSE, TRUE, NOW() - INTERVAL '1 hour'),
('Editor', 'User', 'editor@example.com', 'editor', '$argon2id$v=19$m=65536,t=1,p=4$X3Y4GbVV8pnrXFl/RHL3xw$7DDEkAYfAqeB14mhBFYajtMxGt24h+tIj8fJrmxXeXw', 'editor', FALSE, FALSE, NOW() - INTERVAL '2 days'),
('Viewer', 'User', 'viewer@example.com', 'viewer', '$argon2id$v=19$m=65536,t=1,p=4$X3Y4GbVV8pnrXFl/RHL3xw$7DDEkAYfAqeB14mhBFYajtMxGt24h+tIj8fJrmxXeXw', 'viewer', FALSE, FALSE, NOW() - INTERVAL '5 days'),
('Audit',  'Bot',  'audit@internal',     'auditor','$argon2id$v=19$m=65536,t=1,p=4$X3Y4GbVV8pnrXFl/RHL3xw$7DDEkAYfAqeB14mhBFYajtMxGt24h+tIj8fJrmxXeXw', 'viewer', FALSE, TRUE,  NOW());

-- B) Bulk Users (50)
INSERT INTO users (first_name, last_name, email, username, password, role, inactive_status, mfa_enabled, last_login, user_created_at)
SELECT
    'User' || i::text,
    'AutoGenerated',
    'user' || i::text || '@enterprise.local',
    'user' || i::text,
    '$argon2id$v=19$m=65536,t=1,p=4$X3Y4GbVV8pnrXFl/RHL3xw$7DDEkAYfAqeB14mhBFYajtMxGt24h+tIj8fJrmxXeXw', -- Default password 'admin'
    CASE WHEN i % 5 = 0 THEN 'admin' WHEN i % 3 = 0 THEN 'editor' ELSE 'viewer' END,
    CASE WHEN i % 20 = 0 THEN TRUE ELSE FALSE END,
    CASE WHEN i % 5 = 0 THEN TRUE ELSE FALSE END,
    NOW() - (random() * INTERVAL '30 days'),
    NOW() - (random() * INTERVAL '365 days')
FROM generate_series(1, 46) AS i; -- 4 core users + 46 bulk = 50 total


-- ==================================================================================
-- 2. LOCATIONS (Physical + Logical)
-- ==================================================================================
INSERT INTO locations (name, city, country, address, site_code, timezone, lat, lon) VALUES 
-- Global Major Sites
('Global Tech HQ',     'San Francisco', 'USA',       'Salesforce Tower',      'SFO-HQ',   'America/Los_Angeles', 37.7749, -122.4194),
('Berlin Gigafactory', 'Berlin',        'Germany',   'Am Tesla Grohmann',     'BER-GIGA', 'Europe/Berlin',       52.5200, 13.4050),
('Boston Med Center',  'Boston',        'USA',       'Longwood Med Area',     'BOS-MED',  'America/New_York',    42.3601, -71.0589),
('Shanghai Port Hub',  'Shanghai',      'China',     'Yangshan Port',         'PVG-PORT', 'Asia/Shanghai',       31.2304, 121.4737),
('Oxford St Flagship', 'London',        'UK',        'Oxford Street',         'LON-OXF',  'Europe/London',       51.5074, -0.1278),
('Smart City Control', 'Dubai',         'UAE',       'Museum of the Future',  'DXB-SMRT', 'Asia/Dubai',          25.2048, 55.2708),
('Nordic Energy Hub',  'Oslo',          'Norway',    'Fjord City',            'OSL-NRG',  'Europe/Oslo',         59.9139, 10.7522),
('Tech University',    'Singapore',     'Singapore', 'Clementi Road',         'SIN-UNI',  'Asia/Singapore',      1.3521,  103.8198),
('Deep Space Comms',   'Austin',        'USA',       'SpaceX Boca Chica',     'AUS-SPC',  'America/Chicago',     30.2672, -97.7431),
('5G Edge Core',       'Manchester',    'UK',        'MediaCityUK',           'MAN-5G',   'Europe/London',       53.4808, -2.2426),
-- Cloud Regions
('AWS US-East-1',      'N. Virginia',   'Cloud',     'AWS Availability Zone', 'AWS-USE1', 'America/New_York',    38.8951, -77.0364),
('Azure West Europe',  'Amsterdam',     'Cloud',     'Azure Datacenter',      'AZ-WEU',   'Europe/Amsterdam',    52.3676, 4.9041),
-- Turkey Region
('Istanbul HQ - Maslak',          'Istanbul',  'Turkey', 'Maslak 1453 Plaza, Floor 25',    'IST-HQ',   'Europe/Istanbul', 41.0082, 28.9784),
('Istanbul DC - Esenyurt',        'Istanbul',  'Turkey', 'Esenyurt Data Center Campus, Hall 2', 'IST-DC', 'Europe/Istanbul', 41.0342, 28.6800),
('Istanbul Branch - Kadikoy',     'Istanbul',  'Turkey', 'Bagdat Caddesi No:45',           'IST-BR',   'Europe/Istanbul', 40.9819, 29.0496),
('Ankara Main Office - Sogutozu', 'Ankara',    'Turkey', 'Armada Tower B, Floor 10',       'ANK-HQ',   'Europe/Istanbul', 39.9334, 32.8597),
('Izmir Regional Office',         'Izmir',     'Turkey', 'Folkart Towers A Block',         'IZM-HQ',   'Europe/Istanbul', 38.4237, 27.1428);


-- ==================================================================================
-- 2b. USER LOCATION ACCESS (RBAC Mappings)
-- ==================================================================================
WITH locs AS (
  SELECT id, row_number() OVER (ORDER BY id) AS rn, count(*) OVER () AS total
  FROM locations
),
users_rn AS (
  SELECT id, role, row_number() OVER (ORDER BY id) AS rn
  FROM users
)
INSERT INTO user_location_access (user_id, location_id, permission)
SELECT
    u.id,
    l.id,
    CASE WHEN u.role = 'admin' THEN 'write' ELSE 'read' END
FROM users_rn u
JOIN locs l
  ON u.role = 'admin'
  OR l.rn IN (((u.rn - 1) % l.total) + 1, ((u.rn) % l.total) + 1);


-- ==================================================================================
-- 3. VLANs (1,000)
-- ==================================================================================

-- A) Static Global VLANs
INSERT INTO vlans (vlan_id, name, description, subnet_cidr, gateway_ip, location_id) VALUES
(1,    'Default',             'Factory Default',       '192.168.1.0/24',   '192.168.1.1', NULL),
(10,   'Mgmt_Global',         'Global OOB Management', '10.255.0.0/16',    '10.255.0.1',  NULL),
(5,    'Prov_Network',        'Zero Touch Provisioning', '10.254.0.0/16',  '10.254.0.1',  NULL),
(999,  'Blackhole',           'Security Isolation',    NULL,               NULL,          NULL);

-- B) Bulk VLANs (1,000)
WITH locs AS (
  SELECT id, row_number() OVER (ORDER BY id) AS rn
  FROM locations
),
stats AS (
  SELECT count(*) AS total FROM locations
)
INSERT INTO vlans (vlan_id, name, description, subnet_cidr, gateway_ip, location_id)
SELECT
    1000 + i, 
    'VLAN-' || (1000 + i)::text,
    'Bulk Generated VLAN #' || i::text,
    '10.' || ((i / 255) % 254)::int::text || '.' || (i % 255)::int::text || '.0/24',
    '10.' || ((i / 255) % 254)::int::text || '.' || (i % 255)::int::text || '.1',
    l.id
FROM generate_series(1, 1000) AS i
JOIN stats s ON true
JOIN locs l ON l.rn = (i % s.total) + 1;


-- ==================================================================================
-- 4. DEVICES (10,000 -> 20,000 Interfaces)
-- ==================================================================================

-- A) Static Core Devices
INSERT INTO devices (hostname, ip, model, vendor, os, os_version, role, status, rack_position, serial_number, tags, location_id)
SELECT 'ist-spine-01', '10.34.0.1', 'Nexus 9508', 'Cisco', 'NX-OS', '10.3(2)', 'spine', 'active', 'Rack A01', 'FDO2211AAA', '["core", "spine"]', id FROM locations WHERE site_code = 'IST-HQ';

-- B) Bulk Devices (10,000)
WITH locs AS (
  SELECT id, row_number() OVER (ORDER BY id) AS rn
  FROM locations
),
stats AS (
  SELECT count(*) AS total FROM locations
),
bulk_data AS (
   SELECT i, (i % (SELECT total FROM stats)) + 1 AS loc_rn
   FROM generate_series(1, 10000) AS i
)
INSERT INTO devices (hostname, ip, model, vendor, os, os_version, serial_number, status, role, rack_position, tags, location_id, last_seen)
SELECT
    'bulk-dev-' || lpad(b.i::text, 6, '0'),
    '10.200.' || ((b.i / 254) % 254)::int::text || '.' || (b.i % 254)::int::text,
    'Switch-' || ((b.i % 10) + 1)::text,
    CASE WHEN b.i % 4 = 0 THEN 'Cisco' WHEN b.i % 4 = 1 THEN 'Juniper' WHEN b.i % 4 = 2 THEN 'Arista' ELSE 'Huawei' END,
    CASE WHEN b.i % 4 = 0 THEN 'IOS-XE' WHEN b.i % 4 = 1 THEN 'Junos' WHEN b.i % 4 = 2 THEN 'EOS' ELSE 'VRP' END,
    '17.' || (b.i % 9)::text,
    'SN-BULK-' || b.i,
    CASE WHEN b.i % 20 = 0 THEN 'maintenance' WHEN b.i % 50 = 0 THEN 'offline' ELSE 'active' END,
    CASE WHEN b.i % 50 = 0 THEN 'core' WHEN b.i % 10 = 0 THEN 'distribution' ELSE 'access' END,
    'R' || (b.i % 100)::text,
    jsonb_build_array('bulk', 'generated'),
    l.id,
    NOW() - (random() * INTERVAL '7 days')
FROM bulk_data b
JOIN locs l ON l.rn = b.loc_rn;


-- ==================================================================================
-- 5. INTERFACES (20,000)
-- ==================================================================================
-- 2 Interfaces per Bulk Device
WITH bulk_devs AS (
    SELECT d.id, gs.i, d.hostname
    FROM devices d
    CROSS JOIN generate_series(0, 1) AS gs(i)
    WHERE d.hostname LIKE 'bulk-dev-%'
)
INSERT INTO interfaces (device_id, name, type, status, admin_status, oper_status, speed, speed_mbps, mtu, mode, description, ip_address, mac_address)
SELECT
    id,
    CASE WHEN i = 0 THEN 'Uplink-Eth0' ELSE 'Access-Eth1' END,
    'ethernet',
    'up', 'up', 'up',
    CASE WHEN i = 0 THEN '10Gbps' ELSE '1Gbps' END,
    CASE WHEN i = 0 THEN 10000 ELSE 1000 END,
    1500,
    CASE WHEN i = 0 THEN 'trunk' ELSE 'access' END,
    'Bulk Intf ' || i,
    NULL,
    -- Safe MAC generation using MD5 of ID + interface index
    '02:' ||
    substr(md5(id::text || ':' || i::text), 1, 2) || ':' ||
    substr(md5(id::text || ':' || i::text), 3, 2) || ':' ||
    substr(md5(id::text || ':' || i::text), 5, 2) || ':' ||
    substr(md5(id::text || ':' || i::text), 7, 2) || ':' ||
    substr(md5(id::text || ':' || i::text), 9, 2)
FROM bulk_devs;


-- ==================================================================================
-- 5b. INTERFACE VLAN MAPPINGS
-- ==================================================================================
-- Access interfaces get one native VLAN per site
WITH access_ints AS (
    SELECT i.id AS interface_id, d.location_id,
           row_number() OVER (PARTITION BY d.location_id ORDER BY i.id) AS rn
    FROM interfaces i
    JOIN devices d ON d.id = i.device_id
    WHERE i.name = 'Access-Eth1'
),
loc_vlans AS (
    SELECT id AS vlan_id, location_id,
           row_number() OVER (PARTITION BY location_id ORDER BY vlan_id) AS rn,
           count(*) OVER (PARTITION BY location_id) AS total
    FROM vlans
    WHERE location_id IS NOT NULL
)
INSERT INTO interface_vlans (interface_id, vlan_id, tagging, is_native)
SELECT a.interface_id, v.vlan_id, 'untagged', true
FROM access_ints a
JOIN loc_vlans v
  ON v.location_id = a.location_id
 AND v.rn = ((a.rn - 1) % v.total) + 1;

-- Uplink interfaces get two tagged VLANs per site
WITH uplinks AS (
    SELECT i.id AS interface_id, d.location_id,
           row_number() OVER (PARTITION BY d.location_id ORDER BY i.id) AS rn
    FROM interfaces i
    JOIN devices d ON d.id = i.device_id
    WHERE i.name = 'Uplink-Eth0'
),
loc_vlans AS (
    SELECT id AS vlan_id, location_id,
           row_number() OVER (PARTITION BY location_id ORDER BY vlan_id) AS rn,
           count(*) OVER (PARTITION BY location_id) AS total
    FROM vlans
    WHERE location_id IS NOT NULL
)
INSERT INTO interface_vlans (interface_id, vlan_id, tagging, is_native)
SELECT u.interface_id, v.vlan_id, 'tagged', false
FROM uplinks u
JOIN loc_vlans v
  ON v.location_id = u.location_id
 AND v.rn IN (((u.rn - 1) % v.total) + 1, ((u.rn) % v.total) + 1);


-- ==================================================================================
-- 6. LINKS (Topology) - Explicit Generation
-- ==================================================================================
-- Generate 5000 random links between devices
WITH dev_ints AS (
    SELECT id, device_id, row_number() OVER (ORDER BY random()) AS rn
    FROM interfaces 
    WHERE name = 'Uplink-Eth0' 
    LIMIT 10000 -- Only use uplinks
),
pairs AS (
    SELECT 
        t1.id as a_id,
        t2.id as b_id
    FROM dev_ints t1
    JOIN dev_ints t2 ON t1.rn = t2.rn - 1 -- Chain them: 1-2, 3-4, etc.
    WHERE t1.rn % 2 = 1 -- Non-overlapping pairs
)
INSERT INTO links (a_interface_id, b_interface_id, discovery, status, last_seen)
SELECT
    LEAST(a_id, b_id),
    GREATEST(a_id, b_id),
    'lldp',
    'up',
    NOW()
FROM pairs;


-- ==================================================================================
-- 7. METRICS (Time Series)
-- ==================================================================================
-- 3 snapshots per device over the last 12 hours
WITH snapshots AS (
    SELECT d.id AS device_id, gs.i AS seq
    FROM devices d
    CROSS JOIN generate_series(0, 2) AS gs(i)
)
INSERT INTO device_metrics (device_id, cpu, memory, temp, uptime_seconds, ts)
SELECT
    s.device_id,
    (random() * 80 + 5)::numeric(5,2),
    (random() * 80 + 5)::numeric(5,2),
    (random() * 45 + 20)::numeric(5,2),
    (random() * 900000 + (s.seq * 14400))::bigint,
    NOW() - (s.seq * INTERVAL '4 hours')
FROM snapshots s;


-- ==================================================================================
-- 8. EVENTS
-- ==================================================================================
-- Device events (4,000)
WITH devs AS (
    SELECT id, location_id, row_number() OVER (ORDER BY id) AS rn
    FROM devices
),
stats AS (
    SELECT count(*) AS total FROM devs
),
series AS (
    SELECT generate_series(1, 4000) AS i
)
INSERT INTO events (severity, type, message, device_id, location_id, created_at)
SELECT
    CASE WHEN s.i % 20 = 0 THEN 'critical' WHEN s.i % 10 = 0 THEN 'warning' ELSE 'info' END,
    CASE WHEN s.i % 7 = 0 THEN 'security' ELSE 'system' END,
    'Device event #' || s.i,
    d.id,
    d.location_id,
    NOW() - (s.i % 168) * INTERVAL '1 hour'
FROM series s
JOIN stats st ON true
JOIN devs d ON d.rn = ((s.i - 1) % st.total) + 1;

-- Interface events (2,000)
WITH ints AS (
    SELECT i.id AS interface_id, i.device_id, d.location_id, row_number() OVER (ORDER BY i.id) AS rn
    FROM interfaces i
    JOIN devices d ON d.id = i.device_id
),
stats AS (
    SELECT count(*) AS total FROM ints
),
series AS (
    SELECT generate_series(1, 2000) AS i
)
INSERT INTO events (severity, type, message, device_id, interface_id, location_id, created_at)
SELECT
    CASE WHEN s.i % 15 = 0 THEN 'critical' WHEN s.i % 6 = 0 THEN 'warning' ELSE 'info' END,
    'interface',
    'Interface event #' || s.i,
    t.device_id,
    t.interface_id,
    t.location_id,
    NOW() - (s.i % 72) * INTERVAL '1 hour'
FROM series s
JOIN stats st ON true
JOIN ints t ON t.rn = ((s.i - 1) % st.total) + 1;

-- ==================================================================================
-- 9. AUDIT LOGS
-- ==================================================================================
-- Device audit trail (150)
WITH users_rn AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn, count(*) OVER () AS total
    FROM users
),
devs AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn, count(*) OVER () AS total
    FROM devices
),
series AS (
    SELECT generate_series(1, 150) AS i
)
INSERT INTO audit_logs (user_id, action, resource_type, resource_id, ip_address, created_at)
SELECT
    u.id,
    CASE WHEN s.i % 3 = 0 THEN 'create' WHEN s.i % 3 = 1 THEN 'update' ELSE 'delete' END,
    'device',
    d.id,
    '10.0.0.' || (s.i % 255),
    NOW() - (s.i * INTERVAL '5 minutes')
FROM series s
JOIN users_rn u ON u.rn = ((s.i - 1) % u.total) + 1
JOIN devs d ON d.rn = ((s.i - 1) % d.total) + 1;

-- Interface audit trail (100)
WITH users_rn AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn, count(*) OVER () AS total
    FROM users
),
ints AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn, count(*) OVER () AS total
    FROM interfaces
),
series AS (
    SELECT generate_series(1, 100) AS i
)
INSERT INTO audit_logs (user_id, action, resource_type, resource_id, ip_address, created_at)
SELECT
    u.id,
    'update',
    'interface',
    i.id,
    '10.0.1.' || (s.i % 255),
    NOW() - (s.i * INTERVAL '7 minutes')
FROM series s
JOIN users_rn u ON u.rn = ((s.i - 1) % u.total) + 1
JOIN ints i ON i.rn = ((s.i - 1) % i.total) + 1;

-- Location audit trail (50)
WITH users_rn AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn, count(*) OVER () AS total
    FROM users
),
locs AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn, count(*) OVER () AS total
    FROM locations
),
series AS (
    SELECT generate_series(1, 50) AS i
)
INSERT INTO audit_logs (user_id, action, resource_type, resource_id, ip_address, created_at)
SELECT
    u.id,
    'update',
    'location',
    l.id,
    '10.0.2.' || (s.i % 255),
    NOW() - (s.i * INTERVAL '10 minutes')
FROM series s
JOIN users_rn u ON u.rn = ((s.i - 1) % u.total) + 1
JOIN locs l ON l.rn = ((s.i - 1) % l.total) + 1;
